version: '3.5'

services:
    app:
        build:
            context: .
        command:
            - gunicorn
            - blog.wsgi
            - -b
            - 0.0.0.0:8000
        ports:
            - '8000:8000'
        volumes:
            - '.:/srv/app'
        environment:
            DEBUG: 'True'
            DATABASE_URL: psql://django:django@db:5432/blog
        env_file: .dockerenv
        networks:
            blog_net:
                ipv4_address: 172.18.0.2
    db:
        image: postgres:latest
        volumes:
            - 'db-volume:/var/lib/postgresql/data'
        environment:
            POSTGRES_USER: django
            POSTGRES_PASSWORD: django
            POSTGRES_DB: blog
        networks:
            blog_net:
                ipv4_address: 172.18.0.3

volumes:
    db-volume:
        name: blog_db_volume

networks:
    blog_net:
        ipam:
            config:
                - subnet: 172.18.0.0/16
