version: '3.5'

services:
    app:
        build:
            context: .
        command:
            - gunicorn
            - blog.wsgi
            - -b
            - 0.0.0.0:8000
        ports:
            - '8000:8000'
        volumes:
            - '.:/srv/app'
    db:
        image: postgres:latest
        ports:
            - '5431:5432'
    


